# Generated by Django 2.2.7 on 2019-12-05 23:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.Answer')),
            ],
            bases=('shared.answer',),
        ),
        migrations.CreateModel(
            name='BundleQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.Question')),
            ],
            bases=('shared.question',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_packages', to='shared.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_packages', to='shared.User')),
            ],
        ),
        migrations.CreateModel(
            name='PackageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_units', to='bundle.BundleAnswer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_units', to='bundle.Package')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_units', to='bundle.BundleQuestion')),
            ],
        ),
    ]
